package cn.lcdiao.ssm.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-06-05T00:47:24.920+08:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://service.ssm.lcdiao.cn/", name = "UserService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserService {

    @WebMethod
    @RequestWrapper(localName = "list", targetNamespace = "http://service.ssm.lcdiao.cn/", className = "cn.lcdiao.ssm.service.List")
    @ResponseWrapper(localName = "listResponse", targetNamespace = "http://service.ssm.lcdiao.cn/", className = "cn.lcdiao.ssm.service.ListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<cn.lcdiao.ssm.service.User> list()
;

    @WebMethod
    @RequestWrapper(localName = "insertSelective", targetNamespace = "http://service.ssm.lcdiao.cn/", className = "cn.lcdiao.ssm.service.InsertSelective")
    @ResponseWrapper(localName = "insertSelectiveResponse", targetNamespace = "http://service.ssm.lcdiao.cn/", className = "cn.lcdiao.ssm.service.InsertSelectiveResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int insertSelective(

        @WebParam(name = "arg0", targetNamespace = "")
        cn.lcdiao.ssm.service.User arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getUser", targetNamespace = "http://service.ssm.lcdiao.cn/", className = "cn.lcdiao.ssm.service.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://service.ssm.lcdiao.cn/", className = "cn.lcdiao.ssm.service.GetUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cn.lcdiao.ssm.service.User getUser(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @RequestWrapper(localName = "insert", targetNamespace = "http://service.ssm.lcdiao.cn/", className = "cn.lcdiao.ssm.service.Insert")
    @ResponseWrapper(localName = "insertResponse", targetNamespace = "http://service.ssm.lcdiao.cn/", className = "cn.lcdiao.ssm.service.InsertResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int insert(

        @WebParam(name = "arg0", targetNamespace = "")
        cn.lcdiao.ssm.service.User arg0
    );
}
