
package cn.lcdiao.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IWeatherServiceImplService", targetNamespace = "http://webservice.lcdiao.cn/", wsdlLocation = "http://localhost:8080/weatherService?wsdl")
public class IWeatherServiceImplService
    extends Service
{

    private final static URL IWEATHERSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException IWEATHERSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName IWEATHERSERVICEIMPLSERVICE_QNAME = new QName("http://webservice.lcdiao.cn/", "IWeatherServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/weatherService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IWEATHERSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        IWEATHERSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public IWeatherServiceImplService() {
        super(__getWsdlLocation(), IWEATHERSERVICEIMPLSERVICE_QNAME);
    }

    public IWeatherServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IWEATHERSERVICEIMPLSERVICE_QNAME, features);
    }

    public IWeatherServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, IWEATHERSERVICEIMPLSERVICE_QNAME);
    }

    public IWeatherServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IWEATHERSERVICEIMPLSERVICE_QNAME, features);
    }

    public IWeatherServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IWeatherServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IWeatherServiceImpl
     */
    @WebEndpoint(name = "IWeatherServiceImplPort")
    public IWeatherServiceImpl getIWeatherServiceImplPort() {
        return super.getPort(new QName("http://webservice.lcdiao.cn/", "IWeatherServiceImplPort"), IWeatherServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWeatherServiceImpl
     */
    @WebEndpoint(name = "IWeatherServiceImplPort")
    public IWeatherServiceImpl getIWeatherServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.lcdiao.cn/", "IWeatherServiceImplPort"), IWeatherServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IWEATHERSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw IWEATHERSERVICEIMPLSERVICE_EXCEPTION;
        }
        return IWEATHERSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
