package cn.lcdiao.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-06-03T11:07:23.333+08:00
 * Generated source version: 3.3.6
 *
 */
@WebServiceClient(name = "IWeatherServiceService",
                  wsdlLocation = "http://localhost:8888/weatherService?wsdl",
                  targetNamespace = "http://webservice.lcdiao.cn/")
public class IWeatherServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.lcdiao.cn/", "IWeatherServiceService");
    public final static QName IWeatherServicePort = new QName("http://webservice.lcdiao.cn/", "IWeatherServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8888/weatherService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IWeatherServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8888/weatherService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IWeatherServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IWeatherServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IWeatherServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public IWeatherServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IWeatherServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IWeatherServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IWeatherService
     */
    @WebEndpoint(name = "IWeatherServicePort")
    public IWeatherService getIWeatherServicePort() {
        return super.getPort(IWeatherServicePort, IWeatherService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWeatherService
     */
    @WebEndpoint(name = "IWeatherServicePort")
    public IWeatherService getIWeatherServicePort(WebServiceFeature... features) {
        return super.getPort(IWeatherServicePort, IWeatherService.class, features);
    }

}
