
package cn.lcdiao.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IWeatherServiceImpl", targetNamespace = "http://webservice.lcdiao.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IWeatherServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "query", targetNamespace = "http://webservice.lcdiao.cn/", className = "cn.lcdiao.webservice.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://webservice.lcdiao.cn/", className = "cn.lcdiao.webservice.QueryResponse")
    @Action(input = "http://webservice.lcdiao.cn/IWeatherServiceImpl/queryRequest", output = "http://webservice.lcdiao.cn/IWeatherServiceImpl/queryResponse")
    public String query(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "other", targetNamespace = "http://webservice.lcdiao.cn/", className = "cn.lcdiao.webservice.Other")
    @ResponseWrapper(localName = "otherResponse", targetNamespace = "http://webservice.lcdiao.cn/", className = "cn.lcdiao.webservice.OtherResponse")
    @Action(input = "http://webservice.lcdiao.cn/IWeatherServiceImpl/otherRequest", output = "http://webservice.lcdiao.cn/IWeatherServiceImpl/otherResponse")
    public String other();

}
