package cn.lcdiao;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-06-04T15:58:29.091+08:00
 * Generated source version: 3.3.6
 *
 */
@WebServiceClient(name = "IDreamServiceService",
                  wsdlLocation = "http://localhost:8080/ws/DreamService?wsdl",
                  targetNamespace = "http://lcdiao.cn/")
public class IDreamServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://lcdiao.cn/", "IDreamServiceService");
    public final static QName IDreamServicePort = new QName("http://lcdiao.cn/", "IDreamServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ws/DreamService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IDreamServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ws/DreamService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IDreamServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IDreamServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IDreamServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public IDreamServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IDreamServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IDreamServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IDreamService
     */
    @WebEndpoint(name = "IDreamServicePort")
    public IDreamService getIDreamServicePort() {
        return super.getPort(IDreamServicePort, IDreamService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDreamService
     */
    @WebEndpoint(name = "IDreamServicePort")
    public IDreamService getIDreamServicePort(WebServiceFeature... features) {
        return super.getPort(IDreamServicePort, IDreamService.class, features);
    }

}
